--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 17.2

-- Started on 2025-06-26 09:09:30

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16398)
-- Name: concerts; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.concerts (
    id bigint NOT NULL,
    date character varying(255),
    description character varying(255),
    heure character varying(255),
    image character varying(255),
    lien character varying(255),
    nom character varying(255),
    origine character varying(255),
    scene character varying(255),
    "time" character varying(255)
);


ALTER TABLE public.concerts OWNER TO myuser;

--
-- TOC entry 216 (class 1259 OID 16403)
-- Name: concerts_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.concerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.concerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3370 (class 0 OID 16398)
-- Dependencies: 215
-- Data for Name: concerts; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.concerts (id, date, description, heure, image, lien, nom, origine, scene, "time") FROM stdin;
1	16 Juin	Ce projet musical suisse puise son énergie dans les arpèges violents et dissonants du Black Metal et des sons froids de la musique industrielle.	20:00	https://www.verdammnis.com/img/uploads/2024/08/versatile.jpeg	https://www.versatilemetalband.com/	Versatile	Europe	nord	\N
3	15 Juin	NAPALM DEATH est un groupe de metal extrême dont le nom est synonyme de musique lourde poussée à son paroxysme.	21:00	https://www.metalzone.fr/wp-content/uploads/2023/09/NAPALMDEATH_MOTOC23-19-768x512.jpg	https://napalmdeath.org/	Napalm death	Europe	principale	\N
4	16 Juin	Babymetal, stylisé BABYMETAL, est un groupe de J-pop et heavy metal japonais, originaire de Tokyo. Formé en 2010, il est composé de trois jeunes idoles japonaises et produit par agence de talent Amuse, Inc.	18:00	https://www.metalzone.fr/wp-content/uploads/2019/07/Babymetal.jpg	https://babymetal.com/mob/index.php?site=TO&ima=2604	Babymetal	Asie	sud	\N
10	14 juin	De riffs destructeurs en tensions qui éclatent orages de distorsions, Great Falls portent somme toute très bien leur nom.	20:00	https://www.brooklynvegan.com/wp-content/uploads/2023/02/20/attachment-great-falls.jpeg	https://www.facebook.com/GreatFallsNoise/	Great Falls	Amerique	principale	\N
9	14 juin	Arka n Asrafokor, un groupe de métal africain, est reconnu comme un précurseur dans la scène musicale du continent.	18:00	https://echoesanddust.com/wp-content/uploads/2020/10/84183494_3759271894090573_4725852764620455936_o.jpg	https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.fr%2FDzikkuh-ArkaN-Asrafokor%2Fdp%2FB0D184YS3B&psig=AOvVaw1xxvv6lUBlSMu3pp6GzcEN&ust=1748966096892000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMDAvMuM040DFQAAAAAdAAAAABAW	Arka’n Asrafokor	Afrique	ouest	\N
\.


--
-- TOC entry 3377 (class 0 OID 0)
-- Dependencies: 216
-- Name: concerts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.concerts_id_seq', 1, false);


--
-- TOC entry 3226 (class 2606 OID 16427)
-- Name: concerts concerts_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.concerts
    ADD CONSTRAINT concerts_pkey PRIMARY KEY (id);


-- Completed on 2025-06-26 09:09:43

--
-- PostgreSQL database dump complete
--

